# Generated by Django 5.0.6 on 2026-08-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentcallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identifiant stable utilisé par le frontend (ex. « kharandi-abacus »). Ne jamais le modifier après mise en production.', max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.CharField(choices=[('MENSUEL', 'Mensuel'), ('ANNUEL', 'Annuel'), ('GRATUIT', 'Gratuit'), ('SEMESTRIEL', 'Semestriel'), ('PONCTUEL', 'Paiement unique')], max_length=12),
        ),
    ]
