# Generated by Django 5.0.6 on 2026-08-19 12:32

import django.db.models.deletion
import django.utils.timezone
import users.kyc_storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_options_profile_delivery_zone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorKYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name="Nom complet (tel qu'écrit sur la pièce)")),
                ('document_type', models.CharField(choices=[('CNI', "Carte nationale d'identité"), ('PASSEPORT', 'Passeport'), ('PERMIS', 'Permis de conduire'), ('CARTE_ETU', "Carte d'étudiant")], default='CNI', max_length=12, verbose_name='Type de pièce')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de la pièce')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse / quartier')),
                ('diploma', models.CharField(blank=True, max_length=150, verbose_name='Diplôme le plus élevé')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name="Années d'expérience")),
                ('document_front', models.FileField(storage=users.kyc_storage.stockage_kyc, upload_to=users.kyc_storage.chemin_document_kyc, validators=[users.kyc_storage.valider_document_kyc], verbose_name="Pièce d'identité (recto)")),
                ('document_back', models.FileField(blank=True, null=True, storage=users.kyc_storage.stockage_kyc, upload_to=users.kyc_storage.chemin_document_kyc, validators=[users.kyc_storage.valider_document_kyc], verbose_name="Pièce d'identité (verso)")),
                ('selfie', models.FileField(blank=True, null=True, storage=users.kyc_storage.stockage_kyc, upload_to=users.kyc_storage.chemin_document_kyc, validators=[users.kyc_storage.valider_document_kyc], verbose_name='Photo du visage (selfie)')),
                ('diploma_file', models.FileField(blank=True, null=True, storage=users.kyc_storage.stockage_kyc, upload_to=users.kyc_storage.chemin_document_kyc, validators=[users.kyc_storage.valider_document_kyc], verbose_name='Justificatif de diplôme')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Refusé')], db_index=True, default='PENDING', max_length=10, verbose_name='Statut')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Déposé le')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Examiné le')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif du refus')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes internes (non visibles du répétiteur)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Examiné par')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_kyc', to=settings.AUTH_USER_MODEL, verbose_name='Répétiteur')),
            ],
            options={
                'verbose_name': 'Dossier KYC répétiteur',
                'verbose_name_plural': 'Dossiers KYC répétiteurs',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='users_tutor_status_ec563d_idx')],
            },
        ),
    ]
