# Generated by Django 5.0.6 on 2026-08-21 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_tutorkyc'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=128, unique=True)),
                ('nonce', models.CharField(max_length=128)),
                ('code_verifier', models.CharField(max_length=128)),
                ('platform', models.CharField(default='web', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'état OAuth Google',
                'verbose_name_plural': 'états OAuth Google',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sub', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='identifiant Google (sub)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email Google')),
                ('email_verified', models.BooleanField(default=False, verbose_name='email vérifié par Google')),
                ('given_name', models.CharField(blank=True, max_length=150, verbose_name='prénom Google')),
                ('family_name', models.CharField(blank=True, max_length=150, verbose_name='nom Google')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='date de liaison')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='dernière connexion Google')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_account', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur Kharandi')),
            ],
            options={
                'verbose_name': 'compte Google lié',
                'verbose_name_plural': 'comptes Google liés',
                'ordering': ('-linked_at',),
            },
        ),
        migrations.CreateModel(
            name='GoogleAuthTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('LOGIN', 'Connexion'), ('SIGNUP', 'Inscription à compléter')], max_length=10)),
                ('google_sub', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_verified', models.BooleanField(default=False)),
                ('given_name', models.CharField(blank=True, max_length=150)),
                ('family_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "ticket d'authentification Google",
                'verbose_name_plural': "tickets d'authentification Google",
                'ordering': ('-created_at',),
            },
        ),
    ]
