# Generated by Django 5.0.6 on 2026-08-19 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_orderitem_id'),
        ('payments', '0004_plan_slug_alter_plan_features_alter_plan_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='payments.plan'),
        ),
    ]
