# Generated by Django 5.0.6 on 2026-07-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.PositiveIntegerField(default=10, help_text='Pourcentage de réduction'),
        ),
    ]
