# Generated by Django 5.0.6 on 2026-07-15 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_document_content'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='learning_do_search__ebacef_gin',
            old_name='learning_do_search__idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='learning.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
