# Generated by Django 5.0.6 on 2026-08-10 13:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_readingprogress_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('university', models.CharField(max_length=255)),
                ('program_name', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField(blank=True)),
                ('deadline', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Bourse d'étude",
                'verbose_name_plural': "Bourses d'études",
                'ordering': ['country', 'university'],
            },
        ),
    ]
