# Generated by Django 5.0.6 on 2026-07-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuineaKnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('GEOGRAPHY', 'Géographie'), ('HISTORY', 'Histoire'), ('CULTURE', 'Cultures et langues'), ('EDUCATION', 'Éducation'), ('ECONOMY', 'Économie'), ('ENVIRONMENT', 'Environnement'), ('INSTITUTIONS', 'Institutions')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('source_title', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=500)),
                ('source_published_on', models.DateField(blank=True, null=True)),
                ('verified_on', models.DateField()),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Connaissance sur la Guinée',
                'verbose_name_plural': 'Connaissances sur la Guinée',
                'ordering': ['-priority', 'title'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='ai_features_is_acti_78cbb6_idx'), models.Index(fields=['priority'], name='ai_features_priorit_32a647_idx')],
            },
        ),
    ]
